baseURL = 'https://thuhan01.github.io/'
languageCode = 'en'
title = 'Karma Blog'
theme = 'hugo-theme-reimu'

defaultContentLanguage = 'en'
[languages]
[languages.vi]
  languageName = 'Tiếng Việt'
  weight = 1

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

[markup.highlight]
guessSyntax = true
noClasses = false

home = ["HTML", "RSS"]
